[package]
name = "baremetalisp"
version = "0.1.0"
authors = ["Yuuki Takano <ytakanoster@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
opt-level = 2
lto = true
panic = "abort"

[profile.release]
opt-level = 2
lto = true
panic = "abort"

[lib]
crate-type = ["staticlib"]

[features]
raspi2 = []
raspi3 = []
raspi4 = []
pine64 = []
